name: Deploy

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    unit-tests:
        name: Build
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Node
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'

        - name: Cache node modules
          uses: actions/cache@v2
          env:
              cache-name: npm-cache
          with:
              path: ~/.npm
              key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-${{ env.cache-name }}-

        - name: Pull down dependencies
          run: npm install

        - name: Run unit tests
          run: npm run test:ci
